version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: toy_project_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: toy
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - toy_project_mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always

volumes:
  toy_project_mysql_data:
