version: '3.8'

services:
  toy-commerce-mysql:
    image: mysql:8.0
    platform: linux/arm64/v8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: toy
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - toy_commerce_mysql_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf
    command: --default-authentication-plugin=mysql_native_password
    restart: always

volumes:
  toy_commerce_mysql_data:
  redis_data:
