spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/toy?useSSL=false&serverTimezone=UTC
    username: root
    password: password

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        use_sql_comments: true
        jdbc:
          time_zone: UTC
          batch_size: 30

    open-in-view: false

  data:
    web:
      pageable:
        max-page-size: 100

server:
  port: 8080

logging:
  level:
    root: INFO
    com.example: DEBUG
