spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: UTC
          batch_size: 30
  data:
    web:
      pageable:
        max-page-size: 100

logging:
  level:
    root: INFO
    me.ktkoo.toy: DEBUG
jwt:
  expiry:
    duration: "1800000" # 1000 * 60 * 30 // 30분
  secret: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"