spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: UTC
          batch_size: 50
          fetch_size: 50
    open-in-view: false

  data:
    web:
      pageable:
        max-page-size: 100
#logging:
#  level:
#    org:
#      springframework: debug
#    root: INFO
#    me.ktkoo: DEBUG
jwt:
  expiry:
    duration: "1800000" # 1000 * 60 * 30 // 30분
  secret: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"