spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/toy?useSSL=false&serverTimezone=UTC
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: UTC
          batch_size: 30
  data:
    web:
      pageable:
        max-page-size: 100

server:
  port: 8080

logging:
  level:
    root: INFO
    com.example: DEBUG
jwt:
  expiry:
    duration: "1800000" # 1000 * 60 * 30 // 30분
  secret: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"