spring:
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: UTC
          batch_size: 30

  data:
    web:
      pageable:
        max-page-size: 100

server:
  port: 8080

logging:
  level:
    root: INFO
    com.example: DEBUG
jwt:
  expiry:
    duration: "1800000" # 1000 * 60 * 30 // 30분
  secret: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"