### 장바구니 등록

POST http://localhost:8080/api/carts
Content-Type: application/json

{
  "userId": 1,
  "productId": 1,
  "quantity": 1
}

### 장바구니 조회

GET http://localhost:8080/api/carts/1
Content-Type: application/json
