### 상품 등록
POST http://localhost:8080/api/products
Content-Type: application/json

{
  "name": "상품명",
  "price": 1000000,
  "stockQuantity": 1000
}

### 상품 조뢰
GET http://localhost:8080/api/product?ssize=3&page=2
Content-Type: application/json
