@baseUrl=http://localhost:8080

### 사용자 등록
POST {{baseUrl}}/api/users
Content-Type: application/json

{
  "username": "tkkoo",
  "email": "test@toy.com",
  "password": "Pw1234!@#$",
  "phoneNumber": "+82 10 0000 0000"
}

### jwt 토큰 발급
POST {{baseUrl}}/auth
Content-Type: application/json

{
  "username": "tkkoo",
  "password": "Pw1234!@#$"
}
> {%
    client.global.set("auth_token", response.body);
%}

### 주무 목록 조회
GET {{baseUrl}}/api/orders
Content-Type: application/json
Authorization: Bearer {{auth_token}}

### 상품 목록 조회
GET {{baseUrl}}/api/products
Content-Type: application/json

### 상품 상세 조회
GET {{baseUrl}}/api/products/1
Content-Type: application/json

### 물건 하나 주문
POST {{baseUrl}}/api/orders/newOrder
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "productId": 1,
  "quantity": 2
}

### 장바구니 등록
POST {{baseUrl}}/api/carts
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "productId": 1,
  "quantity": 2
}